### ISSUE TITLE
👋🏻 are you open to modern javascript/typescript formatting?

### ISSUE THREAD

**Issue by peterpme** [logdna/logdna-winston#36]
Hello!

We recently started using logdna and love the service! That being said, it feels like your code and examples are a bit out-dated:

```
  const levels = {
    error: 0
  , warn: 1
  , info: 2
  , http: 3
  , verbose: 4
  , loquacious: 5
  , ludicrous: 6
  }
```

Would you be open to a pull request that sets up prettier, uses camelCase instead of snake_case for variables and brings it up to speed to the rest of the javascript world?

Thank you.

**Comment by mdeltito** [comment]
Hey @peterpme, thanks for the offer and glad you're enjoying LogDNA! Our code examples adhere to our [eslint-enforced style](https://www.npmjs.com/package/eslint-config-logdna) rather than something like Prettier. Although now that you've pointed it out... there are some inconsistencies with the examples 😅  I've opened #37 to address this.

**Comment by peterpme** [comment]
Thanks for the info @mdeltito!

Some customer feedback (take it/leave it): in the age of prettier and modern javascript, trying to read this code style adds a bit of friction.

If my friend didn't suggest logdna and I stumbled across this on my own, I'd look elsewhere because it gives the impression that its out of date.
